CREATE TABLE `forum_topics` (
  `id` int(11) NOT NULL auto_increment,
  `forum_area_id` int(11) NOT NULL,
  `name` varchar(200) collate utf8_swedish_ci NOT NULL,
  `author_name` varchar(30) collate utf8_swedish_ci default NULL,
  `read_count` int(11) unsigned default NULL,
  `type` smallint(6) default NULL,
  `post_count` int(11) unsigned default NULL,
  `last_post_id` int(11) default NULL,
  `last_poster` varchar(30) collate utf8_swedish_ci default NULL,
  `first_post_id` int(11) default NULL,
  `old_name` varchar(200) collate utf8_swedish_ci default NULL,
  `sticky` smallint(6) default NULL,
  `bind_id` int(11) default NULL,
  `expire` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `author_id` int(11) default NULL,
  `votes` int(11) default NULL,
  `points` int(11) default NULL,
  `read_only` smallint(6) default NULL,
  `created` int(11) default NULL,
  `last_posted` int(11) default NULL,
  `status` smallint(6) default NULL,
  `old_area` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `forum_area_id` (`forum_area_id`),
  CONSTRAINT `forum_topics_forum_area_id` FOREIGN KEY (`forum_area_id`) REFERENCES `forum_areas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;
