CREATE TABLE `venues` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(100) collate utf8_swedish_ci default NULL,
  `homepage` varchar(100) collate utf8_swedish_ci default NULL,
  `description` varchar(50) collate utf8_swedish_ci default NULL,
  `address` varchar(50) collate utf8_swedish_ci default NULL,
  `city_name` varchar(50) collate utf8_swedish_ci default NULL,
  `city_id` int(11) default NULL,
  `zip` varchar(5) collate utf8_swedish_ci default NULL,
  `phone` varchar(25) collate utf8_swedish_ci default NULL,
  `fax` varchar(25) collate utf8_swedish_ci default NULL,
  `latitude` double default NULL,
  `longitude` double default NULL,
  `author_id` int(11) default NULL,
  `event_host` int(11) default NULL,
  `hours` varchar(250) collate utf8_swedish_ci default NULL,
  `info` text collate utf8_swedish_ci,
  `default_image_id` int(11) default NULL,
  `forum_topic_id` int(11) default NULL,
  `created` int(11) default NULL,
  `modified` int(11) default NULL,
  `geo_city_id` int(11) default NULL,
  `foursquare_id` int(11) default NULL,
  `foursquare_category_id` int(11) default NULL,
  `geo_country_id` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `city_id` (`city_id`),
  KEY `author_id` (`author_id`),
  KEY `default_image_id` (`default_image_id`),
  KEY `forum_topic_id` (`forum_topic_id`),
  KEY `geo_city_id` (`geo_city_id`),
  CONSTRAINT `venues_author_id` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `venues_city_id` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `venues_default_image_id` FOREIGN KEY (`default_image_id`) REFERENCES `images` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `venues_forum_topic_id` FOREIGN KEY (`forum_topic_id`) REFERENCES `forum_topics` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `venues_geo_city_id` FOREIGN KEY (`geo_city_id`) REFERENCES `geo_cities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;
