CREATE TABLE `forum_areas` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(150) collate utf8_swedish_ci NOT NULL,
  `description` varchar(250) collate utf8_swedish_ci default NULL,
  `type` smallint(6) unsigned NOT NULL default '1',
  `sort` smallint(6) default '0',
  `post_count` int(11) unsigned default NULL,
  `topic_count` int(11) unsigned default NULL,
  `forum_group_id` int(11) unsigned default NULL,
  `last_topic_id` int(11) unsigned default NULL,
  `access` int(11) default NULL,
  `author_id` int(11) default NULL,
  `bind` varchar(32) collate utf8_swedish_ci default NULL,
  `created` int(11) default NULL,
  `access_read` smallint(6) default '0',
  `access_write` smallint(6) default '0',
  `status` smallint(6) default '0',
  `area_type` smallint(6) default '0',
  PRIMARY KEY  (`id`),
  KEY `forum_group_id` (`forum_group_id`),
  KEY `author_id` (`author_id`),
  CONSTRAINT `forum_areas_author_id` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `forum_areas_forum_group_id` FOREIGN KEY (`forum_group_id`) REFERENCES `forum_groups` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;
